#!/usr/bin/env php
<?php
$ticks = array('▁','▂','▃','▄','▅','▆','▇');
$args  = explode(',', (($argv[1] == '--stdin') ? fgets(fopen('php://stdin', 'r'), 1024) : $argv[1]));
$range = (max($args) - min($args)) + 1;

array_map(function($val) use ($ticks, $args, $range) {
    print $ticks[round((($val - min($args)) / $range) * (count($ticks) - 1))];
}, $args);
print "\n";
